name: git page

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      commit_secret: ${{secrets.COMMIT_SECRET}}
      USER_NAME   : LonelyYeezhiChicken
      USER_EMAIL  : hibary.taiwan@gamil.com
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn Install
        run: yarn install

      - name: deploy
        run: |
          rm -rf node_modules/.cache
          yarn build
          yarn export
          git init
          git config --global user.email  hibary.taiwan@gamil.com
          git config --global user.name chicken-ci
          git status
          git remote add origin https://${{secrets.COMMIT_SECRET}}@github.com/LonelyYeezhiChicken/rpg-game-v1.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy game to gh-pages" 
          git push origin gh-pages -f
          echo 🤘 deploy gh-pages complete.
